name: Windows

on:
  push:
    branches:
      - main
      - feature/*
      - merge*
      - fix/*
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: ${{ matrix.os }} shrd=${{ matrix.shared }} java=${{ matrix.cmake.java }} dotnet=${{ matrix.cmake.dotnet }} python=${{ matrix.cmake.python }}-${{ matrix.cmake.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      XPRESSDIR: ${{ github.workspace }}/xpressmp
      XPAUTH_PATH: ${{ github.workspace }}/xpressmp/bin/xpauth.xpr
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        cmake: [
          { java: ON,  dotnet: ON,  python: OFF, python-version: "3.8",  python-dir: "Python309", publish-cxx-or: ON },
          { java: OFF, dotnet: OFF, python: ON,  python-version: "3.8",  python-dir: "Python308", publish-cxx-or: OFF },
          { java: OFF, dotnet: OFF, python: ON,  python-version: "3.9",  python-dir: "Python309", publish-cxx-or: OFF },
          { java: OFF, dotnet: OFF, python: ON,  python-version: "3.10", python-dir: "Python310", publish-cxx-or: OFF },
        ]
    steps:
      - name: Checkout or-tools
        uses: actions/checkout@v4

      - name: Setup .NET 6.0
        if: ${{ matrix.cmake.dotnet == 'ON' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.cmake.python-version }}
          architecture: x64
      - name: Install python3
        run: python3 -m pip install --user mypy-protobuf absl-py setuptools wheel numpy pandas
      - name: Add Python binaries to path Windows
        run: >
          echo "$((Get-Item ~).FullName)/AppData/Roaming/Python/${{ matrix.cmake.python-dir }}/Scripts" |
          Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install SWIG 4.1.1
        shell: pwsh
        run: |
          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.1.1.zip","swigwin-4.1.1.zip");
          Expand-Archive .\swigwin-4.1.1.zip .;
          echo "$((Get-Item .).FullName)/swigwin-4.1.1" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Remove-Item .\swigwin-4.1.1.zip

      - name: Set-up Xpress with pip
        shell: bash
        run: |
          python -m pip install --no-cache-dir xpress==9.0.0
          XPRESS_DIR="${{ env.pythonLocation }}\Lib\site-packages\xpress"
          echo "XPRESSDIR=$XPRESS_DIR" >> $GITHUB_ENV
          echo "XPAUTH_PATH=$XPRESS_DIR\license\community-xpauth.xpr" >> $GITHUB_ENV

      - name: Check cmake
        run: cmake --version
      - name: Configure OR-Tools
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_PYTHON=${{ matrix.cmake.python }}
          -DBUILD_JAVA=${{ matrix.cmake.java }}
          -DBUILD_DOTNET=${{ matrix.cmake.dotnet }}
          -DBUILD_EXAMPLES=ON
          -DBUILD_XPRESS_TEST_AND_EXAMPLES=ON
          -DBUILD_DEPS=ON
          -DBUILD_SAMPLES=OFF
          -DCMAKE_INSTALL_PREFIX="build/install"

      - name: Build OR-Tools windows
        run: >
          cmake --build build 
          --config Release 
          --target ALL_BUILD INSTALL 
          -v -j2

      - name: run tests not xpress
        working-directory: ./build/
        run: >
          ctest -C Release 
          --output-on-failure 
          -E "xpress"

      - name: run tests xpress
        working-directory: ./build/
        run: >
          ctest -V -C Release 
          --output-on-failure 
          -R "xpress"

      - name: set name variables
        id: names
        shell: bash
        run: |
          SHARED=${{ matrix.shared }}
          [ $SHARED == "ON" ] && WITH_SHARED="_shared" || WITH_SHARED="_static"
          OS="_${{ matrix.os }}"
          APPENDIX="${OS}"
          echo "::set-output name=appendix::$APPENDIX"
          APPENDIX_WITH_SHARED="${OS}${WITH_SHARED}"
          echo "::set-output name=appendix_with_shared::$APPENDIX_WITH_SHARED"

      - name: is release created
        shell: bash
        run: |
          release_created=${{ github.event_name == 'release' && github.event.action == 'created' }}
          echo "RELEASE_CREATED=$release_created" >> $GITHUB_ENV

      - name: Get release
        if: ${{ env.RELEASE_CREATED == 'true' }}
        id: get_release
        uses:
          bruceadams/get-release@v1.2.3

      - name: Prepare OR-Tools install
        if: ${{ matrix.cmake.publish-cxx-or == 'ON' }}
        id: or-install
        shell: bash
        run: |
          cd build
          ARCHIVE_NAME="ortools_cxx${{ steps.names.outputs.appendix_with_shared }}.zip"
          ARCHIVE_PATH="${{ github.workspace }}/build/${ARCHIVE_NAME}"
          zip -r "$ARCHIVE_PATH" ./install
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT
          

      - name: Upload OR-Tools install artifact
        uses: actions/upload-artifact@v3
        if: ${{ env.RELEASE_CREATED == 'false' && matrix.cmake.publish-cxx-or == 'ON' }}
        with:
          name: ${{ steps.or-install.outputs.archive_name }}
          path: ${{ steps.or-install.outputs.archive_path }}

      - name: Publish OR-Tools install asset
        if:  ${{ env.RELEASE_CREATED == 'true' && matrix.cmake.publish-cxx-or == 'ON' }}
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.or-install.outputs.archive_path }}
          asset_name: ${{ steps.or-install.outputs.archive_name }}
          asset_content_type: application/zip

      - name: prepare OR-Tools wheel
        if: ${{ matrix.cmake.python == 'ON' }}
        id: wheel
        shell: bash
        run: |
          cd ./build/python/dist
          MY_DIR="ortools_python-${{ matrix.cmake.python-version }}${{ steps.names.outputs.appendix }}"
          mkdir ${MY_DIR}
          cp *.whl "${MY_DIR}"
          ARCHIVE_NAME="${MY_DIR}.zip"
          ARCHIVE_PATH="${{ github.workspace }}/build/${ARCHIVE_NAME}"
          zip -r "${ARCHIVE_PATH}" "${MY_DIR}"
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT

      - name: Upload OR-Tools wheel artifact
        if: ${{ env.RELEASE_CREATED == 'false' && matrix.cmake.python == 'ON' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.wheel.outputs.archive_name }}
          path: ${{ steps.wheel.outputs.archive_path }}
      - name: Publish OR-Tools wheel asset
        if:  ${{ env.RELEASE_CREATED == 'true' && matrix.cmake.python == 'ON' }}
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.wheel.outputs.archive_path }}
          asset_name: ${{ steps.wheel.outputs.archive_name }}
          asset_content_type: application/zip

      - name: prepare OR-Tools jar
        if: ${{ matrix.cmake.java == 'ON' }}
        id: jar
        shell: bash
        run: |
          cd ./build/java
          MY_DIR="ortools_java${{ steps.names.outputs.appendix }}"
          mkdir ${MY_DIR}
          cp ortools-*/target/*.jar "${MY_DIR}"
          ARCHIVE_NAME="${MY_DIR}.zip"
          ARCHIVE_PATH="${{ github.workspace }}/build/${ARCHIVE_NAME}"
          zip -r "${ARCHIVE_PATH}" "${MY_DIR}"
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT

      - name: Upload OR-Tools jar artifact
        if: ${{ env.RELEASE_CREATED == 'false' && matrix.cmake.java == 'ON' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.jar.outputs.archive_name }}
          path: ${{ steps.jar.outputs.archive_path }}
      - name: Publish OR-Tools jar asset
        if:  ${{ env.RELEASE_CREATED == 'true' && matrix.cmake.java == 'ON' }}
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.jar.outputs.archive_path }}
          asset_name: ${{ steps.jar.outputs.archive_name }}
          asset_content_type: application/zip

      - name: prepare OR-Tools dotnet
        if: ${{ matrix.cmake.dotnet == 'ON' }}
        id: dotnet
        shell: bash
        run: |
          cd ./build/dotnet/packages/
          MY_DIR="ortools_dotnet${{ steps.names.outputs.appendix }}"
          mkdir ${MY_DIR}
          cp Google.OrTools.*.nupkg "${MY_DIR}"
          cp Google.OrTools.runtime.*.nupkg "${MY_DIR}"
          ARCHIVE_NAME="${MY_DIR}.zip"
          ARCHIVE_PATH="${{ github.workspace }}/build/${ARCHIVE_NAME}"
          zip -r "${ARCHIVE_PATH}" "${MY_DIR}"
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT

      - name: Upload OR-Tools dotnet artifact
        if: ${{ env.RELEASE_CREATED == 'false' && matrix.cmake.dotnet == 'ON' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.dotnet.outputs.archive_name }}
          path: ${{ steps.dotnet.outputs.archive_path }}
      - name: Publish OR-Tools dotnet asset
        if:  ${{ env.RELEASE_CREATED == 'true' && matrix.cmake.dotnet == 'ON' }}
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.dotnet.outputs.archive_path }}
          asset_name: ${{ steps.dotnet.outputs.archive_name }}
          asset_content_type: application/zip
